apiVersion: apps/v1
kind: Deployment
metadata:
  name: snia
  labels:
    app: snia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snia
  template:
    metadata:
      labels:
        app: snia
    spec:
      containers:
      - name: snia
        image: venkatarr/snia
        ports:
        - containerPort: 3000
